services:
  mongodb:
    image: mongo:7
    container_name: usthi-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  fastapi:
    build: .
    container_name: fastapi-container
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "8000:8000"

volumes:
  mongodata:
